TourManagementSystem/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TourManagementSystem.Models;

namespace TourManagementSystem.Controllers
{
    public class AdminController : Controller
    {
        private TourManagementSystemEntities details = new TourManagementSystemEntities();
        // GET: Admin
        public ActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignIn(AdminSignIn admin)
        {
            var data = details.AdminSignIns.ToList();

            if (ModelState.IsValid)
            {
                foreach (var item in data)
                {
                    if (item.UserName == admin.UserName && item.Password == admin.Password)
                    {
                        return RedirectToAction("AdminHomePage");

                    }
                }
            }

            return View("SignIn");

        }
        public ActionResult AdminHomePage()
        {
            ViewBag.TotalBookings = details.Bookings.Count();
            ViewBag.Pending = details.Bookings.Where(b => b.BookingStatus == "BookingPending").Count();
            ViewBag.Completed = details.Bookings.Where(b => b.BookingStatus == "Success").Count();
            ViewBag.Cancelled = details.Bookings.Where(b => b.BookingStatus == "Cancelled").Count();
            ViewBag.NumberOfTours = details.TourDetails.Count();
            ViewBag.TourBookingUsers = details.Bookings.Select(m => m.Email).Distinct().Count();
            ViewBag.Users = details.SignUps.Select(m => m.Email).Distinct().Count();


            return View();
        }
    }
}

TourManagementSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TourManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TourManagementSystem/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TourManagementSystem.Models;

namespace TourManagementSystem.Controllers
{
    public class TourController : Controller
    {
        // GET: Tour
        private TourManagementSystemEntities details = new TourManagementSystemEntities();
        // GET: Tour
        public ActionResult AppInterface()
        {
            return View();
        }

        public ActionResult SignIn()
        {
            return View("SignIn");
        }
        [HttpPost]
        [ActionName("SignIn")]
        public ActionResult Check(FormCollection formdata)
        {
            //int count = 0;

            var data = details.SignUps.ToList();
            ViewBag.main = formdata["Username"];
            if (ModelState.IsValid)
            {
                foreach (var value in data)
                {
                    if (value.Email == formdata["Username"] && value.Password == formdata["Password"])
                    {

                        Session["Email"] = value.Email;
                        TempData["Email"] = value.Email;

                        return View("Home");
                    }
                }
            }
            ModelState.AddModelError("", "Invalid username and password");


            return View("SignIn");

        }
        public ActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignUp(SignUp datafromUser)
        {
            if (ModelState.IsValid)
            {
                details.SignUps.Add(datafromUser);
                details.SaveChanges();
                return View("SignIn");
            }
            return View("SignUp");


        }
        public ActionResult SignOut()
        {
            Session["Email"] = null;
            return RedirectToAction("SignIn");
        }
        public ActionResult Home()
        {


            return View();
        }
        public ActionResult TourPackageDetails()
        {

            var data = details.TouristPackages.ToList();

            return View("TourPackageDetails", data);
        }
        public ActionResult Details(int id)
        {

            var data = details.TourDetails.Where(x => x.Id == id).ToList();

            return View(data);
        }
        // [Route("Tour/Booking/{name}")]
        public ActionResult Booking(int id)
        {

            var particularData = details.TourDetails.Where(x => x.Id == id).SingleOrDefault();
            ViewBag.Id = particularData.Id;
            ViewBag.name = particularData.TourName;
            ViewBag.TotalPrice = particularData.FoodCost + particularData.HostelCost + particularData.TravellingCost;
            ViewBag.LeaveDate = particularData.LeaveDate;
            ViewBag.ReturnDate = particularData.ReturnDate;
            Session["TourName"] = particularData.TourName;

            //for DropDownList
            var data = details.TouristPackages.ToList();
            ViewBag.data = new SelectList(data, "TouristName", "TouristName");

            return View();
        }
        [HttpPost]
        [ActionName("Booking")]
        public ActionResult Final(Booking book)
        {
            book.TourName = Session["TourName"].ToString();

            book.Email = TempData["Email"].ToString();
            //  var data=details.TourDetails.Where(x => x.TourName == book.TourName).Single();
            // double TotalCost = book.NumberOfTickets*(data.HostelCost + data.FoodCost + data.TravellingCost);
            // book.TotalCost = TotalCost;

            if (!ModelState.IsValid)

            {
                book.BookingStatus = "BookingPending";
                details.Bookings.Add(book);
                details.SaveChanges();
                return RedirectToAction("Dashboard", "UserBookingManage");



            }

            book.BookingStatus = "Success";
            details.Bookings.Add(book);
            details.SaveChanges();
            // return RedirectToAction("Dashboard",Email);
            return RedirectToAction("Dashboard", "UserBookingManage");




        }
        public ActionResult VisitPlace()
        {
            return View();
        }
        [HttpPost]
        public ActionResult VisitPlace(FormCollection search)
        {
            string name = search["place"];
            var data = details.TouristPackages.Where(x => x.TouristName == name).SingleOrDefault();
            return View(data);
        }
        /* [HttpGet]
          public ActionResult Dashboard()
            {

                 string Email = Session["Email"].ToString();

                 var Bookingdata = details.BookingDetails.Where(x => x.Email == Email).ToList();
                 var TourDetailsData = details.TourDetails.ToList();
                 var data = from b in Bookingdata
                            join p in TourDetailsData on b.TourName equals p.TourName into table
                            from p in table.DefaultIfEmpty()
                            select new MultipleTableConnection
                            {
                                Bookings = b,
                                Details = p
                            };



                 return View(data);


            }*/
        /*  public ActionResult ManageBooking()
          {

          }*/
    }
}

TourManagementSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

<div>
    @Html.ActionLink("<<Back To Home", "Home", "Tour","", new {@class="btn btn-primary"})
</div>

TourManagementSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<div>
    @Html.ActionLink("<<Back To Home", "Home","Tour","", new { @class = "btn btn-primary" })
</div>

TourManagementSystem/Views/Home/Index.cshtml
@{
    Layout = null;
}
<style>
    * {
        text-decoration: none;
        color: black
    }

    .main {
        text-align: center;
        color: blue;
        text-shadow: initial;
    }



    body {
        width: 100%;
        padding-bottom: 20px;
        background-size: cover;
        background-repeat: no-repeat;
    }

    div {
        text-align: center;
        ;
    }

    .link {
        text-align: center;
        background-color: bisque;
        padding: 5px;
        border: solid;
        border-radius: 5px;
        margin-top: 40px;
        text-decoration: none;
        color: black;
    }

    .container {
        margin-top: 50px;
    }

    div {
        text-align: center;
    }
</style>
<body style="background-image: url('https://wallpapertag.com/wallpaper/full/5/c/2/141471-gorgerous-travel-background-2560x1440-for-4k.jpg'); ">
    <div class="containter">
        <h3 class="main">WelCome</h3>
        <h3 class="main">To</h3>
        <h1 class="main">TourManagement System</h1>
        <div>
            <button type="button" class="link">@Html.ActionLink("UserPage >>>", "AppInterface", "Tour")</button>
            <button type="button" class="link">@Html.ActionLink("AdminPage >>>", "SignIn", "Admin")</button>
        </div>
    </div>


</body>