TourManagementSystem/Controllers/AdminBookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TourManagementSystem.Models;

namespace TourManagementSystem.Controllers
{
    public class AdminBookingsController : Controller
    {
        private TourManagementSystemEntities db = new TourManagementSystemEntities();

        // GET: AdminBookings
        public ActionResult Index()
        {
            return View(db.Bookings.ToList());
        }

        // GET: AdminBookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: AdminBookings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminBookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Booking_Id,TourName,Name,Email,MobileNumber,Address,NumberOfTickets,TotalCost,BookingStatus")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(booking);
        }

        // GET: AdminBookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            var data = new List<string>() { "Success", "Bookingpending", "Cancelled" };
            ViewBag.BookingStatus = data;
            return View(booking);
        }

        // POST: AdminBookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Booking_Id,TourName,Name,Email,MobileNumber,Address,NumberOfTickets,TotalCost,BookingStatus")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(booking);
        }

        // GET: AdminBookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: AdminBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TourManagementSystem/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TourManagementSystem.Models;

namespace TourManagementSystem.Controllers
{
    public class AdminController : Controller
    {
        private TourManagementSystemEntities details = new TourManagementSystemEntities();
        // GET: Admin
        public ActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignIn(AdminSignIn admin)
        {
            var data = details.AdminSignIns.ToList();

            if (ModelState.IsValid)
            {
                foreach (var item in data)
                {
                    if (item.UserName == admin.UserName && item.Password == admin.Password)
                    {
                        return RedirectToAction("AdminHomePage");

                    }
                }
            }

            return View("SignIn");

        }
        public ActionResult AdminHomePage()
        {
            ViewBag.TotalBookings = details.Bookings.Count();
            ViewBag.Pending = details.Bookings.Where(b => b.BookingStatus == "BookingPending").Count();
            ViewBag.Completed = details.Bookings.Where(b => b.BookingStatus == "Success").Count();
            ViewBag.Cancelled = details.Bookings.Where(b => b.BookingStatus == "Cancelled").Count();
            ViewBag.NumberOfTours = details.TourDetails.Count();
            ViewBag.TourBookingUsers = details.Bookings.Select(m => m.Email).Distinct().Count();
            ViewBag.Users = details.SignUps.Select(m => m.Email).Distinct().Count();


            return View();
        }
    }
}

TourManagementSystem/Controllers/AdminSignUpsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TourManagementSystem.Models;

namespace TourManagementSystem.Controllers
{
    public class AdminSignUpsController : Controller
    {
        private TourManagementSystemEntities db = new TourManagementSystemEntities();

        // GET: AdminSignUps
        public ActionResult Index()
        {
            return View(db.SignUps.ToList());
        }

        // GET: AdminSignUps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SignUp signUp = db.SignUps.Find(id);
            if (signUp == null)
            {
                return HttpNotFound();
            }
            return View(signUp);
        }

        // GET: AdminSignUps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminSignUps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email,Gender,MobileNumber,Password,ConfirmPassword")] SignUp signUp)
        {
            if (ModelState.IsValid)
            {
                db.SignUps.Add(signUp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(signUp);
        }

        // GET: AdminSignUps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SignUp signUp = db.SignUps.Find(id);
            if (signUp == null)
            {
                return HttpNotFound();
            }
            return View(signUp);
        }

        // POST: AdminSignUps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,Gender,MobileNumber,Password,ConfirmPassword")] SignUp signUp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(signUp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(signUp);
        }

        // GET: AdminSignUps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SignUp signUp = db.SignUps.Find(id);
            if (signUp == null)
            {
                return HttpNotFound();
            }
            return View(signUp);
        }

        // POST: AdminSignUps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SignUp signUp = db.SignUps.Find(id);
            db.SignUps.Remove(signUp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TourManagementSystem/Controllers/AdminTourDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TourManagementSystem.Models;

namespace TourManagementSystem.Controllers
{
    public class AdminTourDetailsController : Controller
    {
        private TourManagementSystemEntities db = new TourManagementSystemEntities();

        // GET: AdminTourDetails
        public ActionResult Index()
        {
            return View(db.TourDetails.ToList());
        }

        // GET: AdminTourDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TourDetail tourDetail = db.TourDetails.Find(id);
            if (tourDetail == null)
            {
                return HttpNotFound();
            }
            return View(tourDetail);
        }

        // GET: AdminTourDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminTourDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TourName,TourPlaceDetails,HotelName,HotelDetails,VehicleDetails,TravellingCost,HostelCost,FoodCost,LeaveDate,ReturnDate")] TourDetail tourDetail)
        {
            if (ModelState.IsValid)
            {
                db.TourDetails.Add(tourDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tourDetail);
        }

        // GET: AdminTourDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TourDetail tourDetail = db.TourDetails.Find(id);
            if (tourDetail == null)
            {
                return HttpNotFound();
            }
            return View(tourDetail);
        }

        // POST: AdminTourDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TourName,TourPlaceDetails,HotelName,HotelDetails,VehicleDetails,TravellingCost,HostelCost,FoodCost,LeaveDate,ReturnDate")] TourDetail tourDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tourDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tourDetail);
        }

        // GET: AdminTourDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TourDetail tourDetail = db.TourDetails.Find(id);
            if (tourDetail == null)
            {
                return HttpNotFound();
            }
            return View(tourDetail);
        }

        // POST: AdminTourDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TourDetail tourDetail = db.TourDetails.Find(id);
            db.TourDetails.Remove(tourDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TourManagementSystem/Views/Admin/AdminHomePage.cshtml
@{
    Layout = null;
}

<style>

    .row {
        padding: 30px 100px;
    }
</style>



<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">


<div class="row">
    <h3>
        Admin Control
    </h3>
    <div>
        <div class="col-sm-12 card bg-light" style="margin-bottom: 1rem;">
            <div class="card-body">
                <span class="display-5">Summary</span>
            </div>
            <div>
                <p class="lead">
                    Number of Tours: <strong>@ViewBag.NumberOfTours</strong>.<br />
                    Number of Bookings: <strong>@ViewBag.TotalBookings</strong>.<br />
                    Number of TourBookingUsers: <strong>@ViewBag.TourBookingUsers</strong>.<br />
                    Number of Users: <strong>@ViewBag.Users</strong>.<br />
                    Bills:
                    <ul>
                        <li>PENDING: @ViewBag.pending</li>
                        <li>COMPLETED: @ViewBag.completed</li>
                        <li>CANCELED: @ViewBag.cancelled</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row card-group">
    <div class="col-md-3 card">
        <div class="card-body">
            <h3 class="card-title">
                TourPackages
            </h3>
            <p>
                Add, Edit or Remove TourPackages.
            </p>
            @Html.ActionLink("Access", "Index", "AdminTouristPackages", "", new { @class = "btn btn-primary" })
        </div>
    </div>
    <div class="col-md-3 card">
        <div class="card-body">
            <h3 class="card-title">
                TourDetails
            </h3>
            <p>
                Add, Edit or Remove TourDeatails.
            </p>
            @Html.ActionLink("Access", "Index", "AdminTourDetails", "", new { @class = "btn btn-primary" })
        </div>
    </div>
    <div class="col-md-3 card">
        <div class="card-body">
            <h3 class="card-title">
                Bookings
            </h3>
            <p>
                Add, Edit or Remove Bookings.
            </p>
            @Html.ActionLink("Access", "Index", "AdminBookings", "", new { @class = "btn btn-primary" })
        </div>
    </div>
    <div class="col-md-3 card">
        <div class="card-body">
            <h3 class="card-title">
                Users
            </h3>
            <p>
                Users' Bill status and Information.
            </p>
            @Html.ActionLink("Access", "Index", "AdminSignUps", "", new { @class = "btn btn-primary" })
        </div>
    </div>

</div>

TourManagementSystem/Views/Admin/SignIn.cshtml
@model TourManagementSystem.Models.AdminSignIn

@{
    Layout = null;
}
<style>
    input.input-validation-error,
    select.input-validation-error {
        background-color: aliceblue;
        border: 2px solid #CD0A0A;
    }

    body {
        background-image: url("https://wallpapercave.com/wp/j9rxwNx.jpg")
    }

    .main {
        border-radius: 3px;
        width: 300px;
        height: 240px;
        vertical-align: central;
        margin: auto;
        color: aliceblue;
        text-align: center;
        margin-top: 250px;
        background-color: rgba(0,0,0,0.6);
        padding-top: 20px;
    }

    .button {
        margin-top: 8px;
    }

    .main div {
        margin-top: 8px;
    }
</style>

<body>
    @using (Html.BeginForm("SignIn", "Admin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="main">
            <h4>AdminSignIn</h4>


            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(model => model.UserName, "", new { style = "color:red" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(model => model.Password, "", new { style = "color:red" })
            </div>

            <div class="form-group">
                <div class="button">
                    <input type="submit" value="SignIn" class="btn btn-default" />
                </div>
            </div>
        </div>
    }



    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>